# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deck < Formula
  desc "Lightweight local dev orchestrator"
  homepage "https://github.com/warriorscode/deck"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WarriorsCode/deck/releases/download/v0.1.0/deck_0.1.0_darwin_amd64.tar.gz"
      sha256 "0b1339f119f9d5ba23b793c0cb176ff807b1451cde2f829fcf4f36d7009b071e"

      define_method(:install) do
        bin.install "deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WarriorsCode/deck/releases/download/v0.1.0/deck_0.1.0_darwin_arm64.tar.gz"
      sha256 "b377eada4a18049fdf4f689465ea3b57dd8cfbb4c9cff3ce1cdf844777cf14ed"

      define_method(:install) do
        bin.install "deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WarriorsCode/deck/releases/download/v0.1.0/deck_0.1.0_linux_amd64.tar.gz"
      sha256 "09d42a871473a73820bc3f6c8fa0ba1824e0aa2a6b5097bbc547d4fcce38fbb4"
      define_method(:install) do
        bin.install "deck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WarriorsCode/deck/releases/download/v0.1.0/deck_0.1.0_linux_arm64.tar.gz"
      sha256 "a0c45238bc7ba7fa096ca366d847580212619d958b27a08265b3a7e061c854f7"
      define_method(:install) do
        bin.install "deck"
      end
    end
  end
end
