# This file was generated by GoReleaser. DO NOT EDIT.
cask "deck" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/WarriorsCode/deck/releases/download/v#{version}/deck_#{version}_darwin_amd64.tar.gz"
      sha256 "19d28a037c10d6213c0c32d7d5e35abba461ef6848ae046f1c3d1ddc1f53e3a7"
    end
    on_arm do
      url "https://github.com/WarriorsCode/deck/releases/download/v#{version}/deck_#{version}_darwin_arm64.tar.gz"
      sha256 "7a564b6384a578e5c9dae391e7e489e135b6346b432b7632f898cabb1b96055d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/WarriorsCode/deck/releases/download/v#{version}/deck_#{version}_linux_amd64.tar.gz"
      sha256 "94802a845f834b7b910ef0d6db79ce4b266dbaa546868733c5b16cd8973c7aef"
    end
    on_arm do
      url "https://github.com/WarriorsCode/deck/releases/download/v#{version}/deck_#{version}_linux_arm64.tar.gz"
      sha256 "e8b43564d41975350f83fd2a94b406c2c3c3e830155c2064270801a897e6644e"
    end
  end

  name "deck"
  desc "Lightweight local dev orchestrator"
  homepage "https://github.com/warriorscode/deck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "deck"

  # No zap stanza required

end
