# This file was generated by GoReleaser. DO NOT EDIT.
cask "deck" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/WarriorsCode/deck/releases/download/v#{version}/deck_#{version}_darwin_amd64.tar.gz"
      sha256 "f765ddb57fc6a75a005b3d1d4759ddbecbc0e7b993925b3d65c13c4b407f15a1"
    end
    on_arm do
      url "https://github.com/WarriorsCode/deck/releases/download/v#{version}/deck_#{version}_darwin_arm64.tar.gz"
      sha256 "bf1005402f2a6d4825e686e1077067ac5a41bcd817787681ca94ae307d5f9f00"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/WarriorsCode/deck/releases/download/v#{version}/deck_#{version}_linux_amd64.tar.gz"
      sha256 "5a2ca8b34b411b4ffebe66468fb4eb8a6c0e7c20e0b7fd867c382bddf78b8436"
    end
    on_arm do
      url "https://github.com/WarriorsCode/deck/releases/download/v#{version}/deck_#{version}_linux_arm64.tar.gz"
      sha256 "2553d309371b81ac2fd367c60d3934697f063c0a9856f0cd4e85f5d1e336412e"
    end
  end

  name "deck"
  desc "Lightweight local dev orchestrator"
  homepage "https://github.com/warriorscode/deck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "deck"

  # No zap stanza required

end
