# This file was generated by GoReleaser. DO NOT EDIT.
cask "deck" do
  version "0.6.0"

  on_macos do
    on_intel do
      url "https://github.com/WarriorsCode/deck/releases/download/v#{version}/deck_#{version}_darwin_amd64.tar.gz"
      sha256 "91620461665637427154d7f9c5e5206182a8c52b7d7fb56ba11eb71f9221b064"
    end
    on_arm do
      url "https://github.com/WarriorsCode/deck/releases/download/v#{version}/deck_#{version}_darwin_arm64.tar.gz"
      sha256 "2437af78609b0093573efaae0baf471d6747fc9f0d74c4620b3b07c370ff0ac4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/WarriorsCode/deck/releases/download/v#{version}/deck_#{version}_linux_amd64.tar.gz"
      sha256 "342c9a789618b5364e094352c91a3ac859e638ac44a8ce3ff38c28ad36ac14f2"
    end
    on_arm do
      url "https://github.com/WarriorsCode/deck/releases/download/v#{version}/deck_#{version}_linux_arm64.tar.gz"
      sha256 "c075a25a9d61ebd4c2fa0a48a1071fcdb876a1e6996780242515b833559fde08"
    end
  end

  name "deck"
  desc "Lightweight local dev orchestrator"
  homepage "https://github.com/warriorscode/deck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "deck"

  # No zap stanza required

end
